version: "3.8"

services:
  db:
    image: library/postgres:12.2
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=blogs
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_socket:/var/run/postgresql/
    ports:
      - "5432:5432"
    restart: "no"

  app:
    build: app/
    volumes:
      - ./app:/usr/src/app
      - postgres_socket:/var/run/postgresql/
      - static:/usr/src/app/static/
    command: bash -c "python manage.py collectstatic --no-input &&
                      python manage.py makemigrations --no-input &&
                      python manage.py migrate --no-input &&
                      uwsgi --ini uwsgi.ini"
    ports:
    - "8001:8001"

    depends_on:
      - db

  nginx:
    image: nginx:mainline
    ports:
      - "80:80"
    volumes:
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
      - ./nginx/conf.d/blogs.conf:/etc/nginx/conf.d/00.conf:ro
      - static:/usr/src/app/static:ro
    depends_on:
      - app

volumes:
  static:
  postgres_socket:

